### ISSUE TITLE
Rename travis-ci folder and adapt github actions

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#6066]
We don't use travis anymore but still use the scripts.
So mayber renaming them would make sense

**Comment by matchy233** [comment]
I just had a brief look at the scripts in /tools/travis folder and I feel that it is better to completely re-write them because GHA has some built-in features that function the same as the ci scripts.

e.g. we can do the following to identify OS in GHA

```yaml
#....
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
    #....
      - name: Windows
        run: # Windows specific command
        if: matrix.os == 'windows-latest'

      - name: Unix-like
        run: # Unix specific command
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
    #....
```
