### ISSUE TITLE
check if/how dependabot can be used to automatically update submodules

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#6610]
check if/how dependabot can be used to automatically update submodules.

Reason:
updating contrib or thirdparty repositories always requires us to manually create a PR in the OpenMS repository that updates the submodules.
Automatizing this process prevents that someone forgets this update.

**Comment by timosachsenberg** [comment]
should be possible with something like:
```
version: 2

updates:
  - package-ecosystem: gitsubmodule
    schedule:
        interval: "daily"
    directory: /
```
