### ISSUE TITLE
Setup organization level GitHub secrets and use them

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6716]
Create some bot account or reuse jenkins bot to store its username and token as organization-level secrets.
That we can use them for auto-pushes to PRs, pushes to GH container registry, comment on issues/PRs, labels etc.

Replace occurrences of specific hardcoded users in all actions in all our repos.

Try to exclude dangerous permissions as much as possible.

**Comment by timosachsenberg** [comment]
We currently already seem to have organization level secrets:
![image](https://user-images.githubusercontent.com/5803621/220966356-c76361b7-0bfe-4ef8-bf30-176c43ee1cd1.png)
In the actions I can see that it is used with username jpfeuffer but in the organization it doesn't seem to be associated with a user.
In the actions we indeed specify a user:
```
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: jpfeuffer
          password: ${{ secrets.GH_REGISTRY_TOKEN }}
```
Do you know if the user can be omitted or the organization name can be used?
